table 'Artefact Metadata'
	lineageTag: de4e3a42-a64b-4796-896c-89158c250ff3

	column 'Artefact'
		dataType: string
		lineageTag: b11c7818-2793-44d1-95dc-3c5cee700c81
		summarizeBy: none
		sourceColumn: artefact

		annotation SummarizationSetBy = User

	column 'Synthetic'
		dataType: boolean
		lineageTag: 89a93601-b8ac-43e5-8e62-7966c5537127
		summarizeBy: none
		sourceColumn: synthetic

		annotation SummarizationSetBy = User

	column 'Generated At'
		dataType: string
		lineageTag: ca0e6739-13b8-4e72-ac16-d5401c748beb
		summarizeBy: none
		sourceColumn: generated_at

		annotation SummarizationSetBy = User

	column 'Data Cutoff'
		dataType: string
		lineageTag: c7d04f5e-b68d-4ec6-8491-68e5d05e2319
		summarizeBy: none
		sourceColumn: data_cutoff

		annotation SummarizationSetBy = User

	column 'Code Version'
		dataType: string
		lineageTag: d4818f0e-552e-4a41-ae20-e6812a6880fa
		summarizeBy: none
		sourceColumn: code_version

		annotation SummarizationSetBy = User

	column 'Suppressed Cells'
		dataType: int64
		formatString: 0
		lineageTag: 9227300b-68ce-4afe-8cf5-6bd88a09a803
		summarizeBy: none
		sourceColumn: suppressed_cells

		annotation SummarizationSetBy = User

	partition 'Artefact Metadata' = m
		mode: import
		source =
				let
				    Source = Csv.Document(VintageFile("artefact_metadata.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"artefact", type text}, {"synthetic", type logical}, {"generated_at", type text}, {"data_cutoff", type text}, {"code_version", type text}, {"suppressed_cells", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
