table 'Dim Date'
	lineageTag: c805c9f0-1d7f-4785-943b-a91cd3ee9bec

	column 'Month'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 5029b097-9ace-484a-8a52-4ac081c8e6d8
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = User

	column 'Year'
		dataType: int64
		formatString: 0
		lineageTag: 0df28dfb-1314-4355-8f4d-be395568bc9a
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column 'Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 383e1c39-d81e-41ee-b127-e29d7e177f27
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = User

	column 'Year Quarter'
		dataType: string
		lineageTag: 7698c6b5-2582-4e9b-a062-e945b8328a22
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = User

	column 'Is Quarter End'
		dataType: boolean
		lineageTag: 8ef73ad2-ba87-4933-afb5-f0cde1c858aa
		summarizeBy: none
		sourceColumn: is_quarter_end

		annotation SummarizationSetBy = User

	column 'Economic Period'
		dataType: string
		lineageTag: 60c0ad8d-ba8c-4bf5-a049-15a40b607ba8
		summarizeBy: none
		sourceColumn: economic_period

		annotation SummarizationSetBy = User

	column 'Market Rate Pct'
		dataType: double
		formatString: 0.0%
		lineageTag: fdef433f-4e2f-4f09-ad79-df1c3e566857
		summarizeBy: none
		sourceColumn: market_rate_pct

		annotation SummarizationSetBy = User

	column 'Market Rate Carried Forward'
		dataType: boolean
		lineageTag: dd5f1c1d-8708-4461-9133-90b908f8b72b
		summarizeBy: none
		sourceColumn: market_rate_carried_forward

		annotation SummarizationSetBy = User

	partition 'Dim Date' = m
		mode: import
		source =
				let
				    Source = Csv.Document(VintageFile("dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"month", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"year_quarter", type text}, {"is_quarter_end", type logical}, {"economic_period", type text}, {"market_rate_pct", type number}, {"market_rate_carried_forward", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
