table 'Monitoring Csi'
	lineageTag: 6c0cc705-49c8-4410-bfa7-447782eed7c4

	column 'Feature'
		dataType: string
		lineageTag: a26ba449-ff63-4ccc-b5a2-595db9b4714c
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = User

	column 'Comparison'
		dataType: string
		lineageTag: 6ffbd517-a832-42af-b4c6-8b7a48ae9d6a
		summarizeBy: none
		sourceColumn: comparison

		annotation SummarizationSetBy = User

	column 'CSI'
		dataType: double
		formatString: 0.0%
		lineageTag: e0a25d88-bff1-4c88-9feb-e57a7dc78b55
		summarizeBy: none
		sourceColumn: csi

		annotation SummarizationSetBy = User

	column 'CSI Lo'
		dataType: double
		formatString: 0.0%
		lineageTag: 327fb383-246a-4740-9642-0d6c04d15b3d
		summarizeBy: none
		sourceColumn: csi_lo

		annotation SummarizationSetBy = User

	column 'CSI Hi'
		dataType: double
		formatString: 0.0%
		lineageTag: 23dc58ef-abe7-4f7b-bc47-82198964494d
		summarizeBy: none
		sourceColumn: csi_hi

		annotation SummarizationSetBy = User

	column 'CSI N'
		dataType: int64
		formatString: 0
		lineageTag: 37814923-688d-4cad-b934-f75d12668a71
		summarizeBy: none
		sourceColumn: csi_n

		annotation SummarizationSetBy = User

	column 'CSI Method'
		dataType: string
		lineageTag: 01f47a0d-b88e-42c3-ac87-271190aa6fb4
		summarizeBy: none
		sourceColumn: csi_method

		annotation SummarizationSetBy = User

	column 'Rag'
		dataType: string
		lineageTag: 75ab2777-48f8-4f7f-8c6f-31a4fbee0b2c
		summarizeBy: none
		sourceColumn: rag

		annotation SummarizationSetBy = User

	column 'Synthetic'
		dataType: boolean
		lineageTag: 764a0794-8f77-4ef5-bcd3-79ed99f353eb
		summarizeBy: none
		sourceColumn: synthetic

		annotation SummarizationSetBy = User

	partition 'Monitoring Csi' = m
		mode: import
		source =
				let
				    Source = Csv.Document(VintageFile("monitoring_csi.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"feature", type text}, {"comparison", type text}, {"csi", type number}, {"csi_lo", type number}, {"csi_hi", type number}, {"csi_n", Int64.Type}, {"csi_method", type text}, {"rag", type text}, {"synthetic", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
