table 'Prepayment'
	lineageTag: 89141d5b-d3f0-4a1b-84ea-97c878c4f11b

	column 'Period'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: b9e5e7c1-6f02-46f8-a10e-8bdb40b1f832
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = User

	column 'Cpr'
		dataType: double
		formatString: 0.0000
		lineageTag: 4bd47a15-1eac-475a-9bbf-96a5b7d324eb
		summarizeBy: none
		sourceColumn: cpr

		annotation SummarizationSetBy = User

	column 'Cpr Lo'
		dataType: double
		formatString: 0.0000
		lineageTag: 1a0f4c75-606f-44ad-8dc4-59cbfeb7db2b
		summarizeBy: none
		sourceColumn: cpr_lo

		annotation SummarizationSetBy = User

	column 'Cpr Hi'
		dataType: double
		formatString: 0.0000
		lineageTag: a6dbb61a-74fe-4b7d-b66b-eb55fc927efe
		summarizeBy: none
		sourceColumn: cpr_hi

		annotation SummarizationSetBy = User

	column 'Cpr N'
		dataType: int64
		formatString: 0
		lineageTag: f272c828-6eef-48d8-b735-01b1e9cdca4c
		summarizeBy: none
		sourceColumn: cpr_n

		annotation SummarizationSetBy = User

	column 'Cpr Method'
		dataType: string
		lineageTag: 2065957d-85c7-42fc-9ff9-40fe808c834b
		summarizeBy: none
		sourceColumn: cpr_method

		annotation SummarizationSetBy = User

	column 'Synthetic'
		dataType: boolean
		lineageTag: ba736c68-752b-48b8-a5a9-202aa7e31ca3
		summarizeBy: none
		sourceColumn: synthetic

		annotation SummarizationSetBy = User

	partition 'Prepayment' = m
		mode: import
		source =
				let
				    Source = Csv.Document(VintageFile("prepayment.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"period", type date}, {"cpr", type number}, {"cpr_lo", type number}, {"cpr_hi", type number}, {"cpr_n", Int64.Type}, {"cpr_method", type text}, {"synthetic", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
