table 'Scorecard Pass Rules'
	lineageTag: 514e099b-ce80-4131-92a3-2212a32993eb

	column 'Rule ID'
		dataType: string
		lineageTag: f9b3e2ad-49b4-47da-baab-1c8e07ae8a9c
		summarizeBy: none
		sourceColumn: rule_id

		annotation SummarizationSetBy = User

	column 'Result'
		dataType: string
		lineageTag: b3bb455a-bd0d-4b5f-ba4c-370ade64ebfd
		summarizeBy: none
		sourceColumn: result

		annotation SummarizationSetBy = User

	column 'Evidence'
		dataType: string
		lineageTag: 6fc53a2c-fb78-461e-84df-9afba8b08cab
		summarizeBy: none
		sourceColumn: evidence

		annotation SummarizationSetBy = User

	column 'Synthetic'
		dataType: boolean
		lineageTag: 1872c65d-a48d-4f17-80ef-e365ffe4deac
		summarizeBy: none
		sourceColumn: synthetic

		annotation SummarizationSetBy = User

	partition 'Scorecard Pass Rules' = m
		mode: import
		source =
				let
				    Source = Csv.Document(VintageFile("scorecard_pass_rules.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"rule_id", type text}, {"result", type text}, {"evidence", type text}, {"synthetic", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
