// One plain-English line per term a non-specialist meets on the site. Used by <Term>.
export const GLOSSARY: Record<string, string> = {
  vintage: "All the loans made in one year, followed together as they age.",
  "months on book": "How many months since the loan was made.",
  default: "The borrower stopped paying: 180+ days late, or the loan ended in a loss event.",
  "cumulative default rate": "The share of a year's loans that have defaulted so far.",
  "roll rate": "The share of loans that move from one lateness bucket to another in a month.",
  "95% CI": "The range the true value very likely sits in. Narrow means precise.",
  scorecard: "A points table: each loan feature adds points, and the total gives a risk grade.",
  Gini: "How well the score separates loans that default from those that don't. 0 is a coin flip, 1 is perfect.",
  KS: "The biggest gap between the score curves of defaulted and non-defaulted loans. Higher separates better.",
  PSI: "How much the score mix has shifted between two samples. Under 0.1 means stable.",
  PD: "Probability of default: the chance a loan defaults within a period.",
  LGD: "Loss given default: the share of the loan lost if it defaults.",
  EAD: "Exposure at default: how much is owed when a loan defaults.",
  ECL: "Expected credit loss: PD × LGD × EAD, the provision a lender sets aside.",
  "IFRS 9": "The accounting rule that makes lenders provision for expected, not just incurred, losses.",
  stage: "IFRS 9 buckets: 1 performing, 2 risk has risen a lot, 3 defaulted.",
  RWA: "Risk-weighted assets: exposure scaled by risk, the base for how much capital a bank must hold.",
  backtest: "Checking past predictions against what actually happened.",
  "out of time": "Loans from later years than the model was built on: the honest test.",
  challenger: "An alternative model that must beat the current one under a rule set in advance.",
  "pre-registered": "The pass mark was written down before the result was seen, so it can't be moved.",
};
