"""The fixtures follow the contract, the checker catches violations, and CONTRACTS.md agrees
with the machine-readable specs in tests/contracts.py.

All data here is SYNTHETIC (tests/fixtures/, generated by scripts/make_fixtures.py).
"""

import copy
import json
import re
import sys
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq
import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "extract"))
import build_parquet  # noqa: E402

from tests import contracts as C  # noqa: E402

FIX = ROOT / "tests" / "fixtures"
CONTRACTS_MD = (ROOT / "CONTRACTS.md").read_text(encoding="utf-8")


@pytest.mark.parametrize("name", list(C.MARTS))
def test_fixture_marts_follow_contract(name):
    path = FIX / "marts" / f"{name}.parquet"
    assert C.check_mart(name, path) == []
    assert C.parquet_is_synthetic(path)


@pytest.mark.parametrize("name", list(C.MODEL_OUTPUTS))
def test_fixture_model_outputs_follow_contract(name):
    path = FIX / "models_out" / f"{name}.parquet"
    assert C.check_model_output(name, path) == []
    assert C.parquet_is_synthetic(path)


@pytest.mark.parametrize("name", list(C.ARTEFACTS))
def test_fixture_artefacts_follow_contract(name):
    obj = json.loads((FIX / "artefacts" / f"{name}.json").read_text(encoding="utf-8"))
    assert C.check_artefact(name, obj) == []
    assert obj["synthetic"] is True


def test_raw_fixtures_extract_with_official_layout(tmp_path):
    manifest = build_parquet.build_parquet(FIX / "raw", tmp_path)
    assert len(manifest["files"]) == 8  # 4 vintages x (origination, performance)
    import duckdb

    ids = duckdb.sql(f"SELECT DISTINCT loan_id FROM '{tmp_path.as_posix()}/*.parquet'").fetchall()
    assert ids and all(i[0][5] == "S" for i in ids), "synthetic loan ids carry an S marker"
    cols = pq.read_schema(tmp_path / "perf_2007.parquet").names
    assert len(cols) == 35


def test_synthetic_marker_on_every_fixture_loan_id():
    import duckdb

    bad = duckdb.sql(
        f"SELECT count(*) FROM '{(FIX / 'marts' / 'dim_loan.parquet').as_posix()}' "
        "WHERE substr(loan_id, 6, 1) <> 'S'"
    ).fetchone()[0]
    assert bad == 0


# ---- the checker catches what it should ------------------------------------------------------
def _rewrite(src: Path, dst: Path, fn) -> Path:
    table = fn(pq.read_table(src))
    pq.write_table(table, dst)
    return dst


def test_checker_flags_missing_column_wrong_type_and_extra(tmp_path):
    src = FIX / "marts" / "dim_date.parquet"
    p = _rewrite(src, tmp_path / "a.parquet", lambda t: t.drop(["market_rate_pct"]))
    assert any("missing column market_rate_pct" in e for e in C.check_mart("dim_date", p))
    p = _rewrite(
        src, tmp_path / "b.parquet", lambda t: t.set_column(1, "year", t["year"].cast(pa.string()))
    )
    assert any("column year is string" in e for e in C.check_mart("dim_date", p))
    p = _rewrite(
        src, tmp_path / "c.parquet", lambda t: t.append_column("extra", pa.array([1] * t.num_rows))
    )
    assert any("unexpected column extra" in e for e in C.check_mart("dim_date", p))


def test_checker_flags_duplicate_keys_nulls_and_bad_values(tmp_path):
    src = FIX / "marts" / "dim_date.parquet"
    p = _rewrite(src, tmp_path / "d.parquet", lambda t: pa.concat_tables([t, t.slice(0, 1)]))
    assert any("duplicate key" in e for e in C.check_mart("dim_date", p))

    def bad_period(t):
        vals = t["economic_period"].to_pylist()
        vals[0] = "boom"
        return t.set_column(
            t.schema.get_field_index("economic_period"), "economic_period", pa.array(vals)
        )

    p = _rewrite(src, tmp_path / "e.parquet", bad_period)
    assert any("outside the contract" in e for e in C.check_mart("dim_date", p))

    def null_year(t):
        vals = t["year"].to_pylist()
        vals[0] = None
        return t.set_column(1, "year", pa.array(vals, pa.int64()))

    p = _rewrite(src, tmp_path / "f.parquet", null_year)
    assert any("null(s) in non-null column year" in e for e in C.check_mart("dim_date", p))


def test_checker_flags_bad_artefacts():
    good = json.loads((FIX / "artefacts" / "capital.json").read_text(encoding="utf-8"))
    assert C.check_artefact("capital", good) == []

    missing = copy.deepcopy(good)
    del missing["limits"]
    assert any("missing key limits" in e for e in C.check_artefact("capital", missing))

    extra = copy.deepcopy(good)
    extra["headline"] = 1
    assert any("unexpected key headline" in e for e in C.check_artefact("capital", extra))

    outside = copy.deepcopy(good)
    outside["by_grade"][0]["pd"]["value"] = 5.0
    assert any("outside its interval" in e for e in C.check_artefact("capital", outside))

    no_reason = copy.deepcopy(good)
    no_reason["by_grade"][0]["k"]["ci_method"] = "bootstrap"
    assert any("must start with 'none:'" in e for e in C.check_artefact("capital", no_reason))

    bad_enum = copy.deepcopy(good)
    bad_enum["status"] = "done"
    assert any("not one of" in e for e in C.check_artefact("capital", bad_enum))

    wrong_name = copy.deepcopy(good)
    wrong_name["artefact"] = "ecl"
    assert any("must be 'capital'" in e for e in C.check_artefact("capital", wrong_name))


def test_metric_helper():
    m = C.metric(0.1, 0.05, 0.2, 100, "wilson_95")
    assert C._check_metric(m, "m") == []
    assert C._check_metric(C.metric(3.0, n=3), "m") == []  # count: no interval, reason given
    assert C._check_metric({"value": 1}, "m")


# ---- CONTRACTS.md and the specs agree --------------------------------------------------------
def _section(title: str) -> str:
    m = re.search(rf"^### `{re.escape(title)}`.*?(?=^### |^## |\Z)", CONTRACTS_MD, re.M | re.S)
    assert m, f"CONTRACTS.md has no section ### `{title}`"
    return m.group(0)


@pytest.mark.parametrize("name", list(C.MARTS) + list(C.MODEL_OUTPUTS))
def test_contracts_md_lists_every_column(name):
    spec = C.MARTS.get(name) or C.MODEL_OUTPUTS[name]
    section = _section(name)
    documented = set(re.findall(r"^\| `([a-z0-9_]+)` \|", section, re.M))
    assert documented == set(spec["columns"]), (
        f"{name}: only in spec {set(spec['columns']) - documented}, "
        f"only in CONTRACTS.md {documented - set(spec['columns'])}"
    )


def _keys(spec) -> set[str]:
    out = set()
    if isinstance(spec, dict):
        for k, v in spec.items():
            out.add(k)
            out |= _keys(v)
    elif isinstance(spec, list):
        out |= _keys(spec[0])
    return out


@pytest.mark.parametrize("name", list(C.ARTEFACTS))
def test_contracts_md_documents_every_artefact_field(name):
    section = _section(f"artefacts/{name}.json")
    common = set(C.ENVELOPE) | set(C.PASS_RULES[0])  # documented once under "Common rules"
    missing = sorted(k for k in _keys(C.ARTEFACTS[name]) - common if f"`{k}`" not in section)
    assert not missing, f"{name}: fields not documented in CONTRACTS.md: {missing}"
